package org.GeoRaptor.SpatialView.SupportClasses;

import oracle.jdbc.OracleConnection;

import org.GeoRaptor.OracleSpatial.Metadata.MetadataTool;
import org.GeoRaptor.SpatialView.layers.SVSpatialLayer;

import org.geotools.util.logging.Logger;
import org.geotools.util.logging.Logging;

/*
 * DiscoverGeometryType.java
 *
 * Created on 29/11/2010, 2:38:35 PM
 */

/**
 *
 * @author Simon
 */
public class DiscoverGeometryType extends javax.swing.JDialog {

	private static final long serialVersionUID = -3073679161985595121L;

	private static final Logger LOGGER = Logging.getLogger("org.GeoRaptor.SpatialView.SupportClasses.DiscoverGeometryType");

    protected SVSpatialLayer layer;
    protected OracleConnection conn;
    protected String schema;
    protected String object;
    protected String column;
    protected String geometryType;
    protected boolean CANCELLED = false;

    /** Creates new form DiscoverGeometryType */
    private DiscoverGeometryType(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public DiscoverGeometryType(boolean          _modal,
                                SVSpatialLayer   _layer,
                                OracleConnection _conn,
                                String           _schema,
                                String           _object,
                                String           _column,
                                String           _geometryType) {
      this(null,_modal);
      this.layer = _layer;
      this.conn  = _conn;
      this.schema = _schema;
      this.object = _object;
      this.column = _column;
      this.geometryType = _geometryType;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        pnlDiscover = new javax.swing.JPanel();
        btnReturn = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblPercentage = new javax.swing.JLabel();
        sldrPercentage = new javax.swing.JSlider();
        btnDiscover = new javax.swing.JButton();
        lblGeometryType = new javax.swing.JLabel();
        lblGeometryTypeValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(300, 100));
        setName("discoveryDialog"); // NOI18N
        setResizable(false);

        pnlDiscover.setBorder(javax.swing.BorderFactory.createTitledBorder("Discover Geometry Type"));

        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        btnReturn.setEnabled(false);
        
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblPercentage.setText("Percentage (50%):");

        sldrPercentage.setMajorTickSpacing(25);
        sldrPercentage.setMinorTickSpacing(5);
        sldrPercentage.setPaintLabels(true);
        sldrPercentage.setPaintTicks(true);
        sldrPercentage.setSnapToTicks(true);
        sldrPercentage.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldrPercentageStateChanged(evt);
            }
        });

        btnDiscover.setText("Discover");
        btnDiscover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscoverActionPerformed(evt);
            }
        });

        lblGeometryType.setText("Geometry Type:");

        lblGeometryTypeValue.setText("COLLECTION");

        javax.swing.GroupLayout pnlDiscoverLayout = new javax.swing.GroupLayout(pnlDiscover);
        pnlDiscover.setLayout(pnlDiscoverLayout);
        pnlDiscoverLayout.setHorizontalGroup(
            pnlDiscoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDiscoverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDiscoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlDiscoverLayout.createSequentialGroup()
                        .addGroup(pnlDiscoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGeometryType)
                            .addGroup(pnlDiscoverLayout.createSequentialGroup()
                                .addComponent(lblPercentage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDiscoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDiscoverLayout.createSequentialGroup()
                                .addComponent(sldrPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDiscover))
                            .addComponent(lblGeometryTypeValue)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDiscoverLayout.createSequentialGroup()
                        .addComponent(btnReturn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        pnlDiscoverLayout.setVerticalGroup(
            pnlDiscoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDiscoverLayout.createSequentialGroup()
                .addGroup(pnlDiscoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDiscoverLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDiscover))
                    .addGroup(pnlDiscoverLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPercentage))
                    .addComponent(sldrPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDiscoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGeometryTypeValue)
                    .addComponent(lblGeometryType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDiscoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel)
                    .addComponent(btnReturn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDiscover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDiscover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        this.CANCELLED = false;
        setVisible(false);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.CANCELLED = true;
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDiscoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscoverActionPerformed
        // TODO add your handling code here:
        String layerGType = null;
        try {
            layerGType = 
                MetadataTool.getLayerGeometryType(this.conn,
                                                 this.schema,
                                                 this.object,
                                                 this.column,
                                                 this.sldrPercentage.getValue(),
                                                 0);
        } catch (Exception e) {
            LOGGER.warn("DiscoverGeometryType: " + e.toString());
        }
        btnReturn.setEnabled(true);
        if ( layerGType == null ) {
            return;
        }
        this.lblGeometryTypeValue.setText(layerGType);
    }//GEN-LAST:event_btnDiscoverActionPerformed

    private void sldrPercentageStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldrPercentageStateChanged
        // TODO add your handling code here:
        this.lblPercentage.setText("Percentage (" + sldrPercentage.getValue() + "%)");
    }//GEN-LAST:event_sldrPercentageStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDiscover;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel lblGeometryType;
    private javax.swing.JLabel lblGeometryTypeValue;
    private javax.swing.JLabel lblPercentage;
    private javax.swing.JPanel pnlDiscover;
    private javax.swing.JSlider sldrPercentage;
    // End of variables declaration//GEN-END:variables

    public boolean wasCancelled() {
        return this.CANCELLED;      
    }
    
    public String getGeometryValue() {
        return this.lblGeometryTypeValue.getText();
    }

}
